apiVersion: apps/v1
kind: Deployment
metadata:
  name: ""
spec:
  selector:
    matchLabels:
      app: ""
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ""
    spec:
      containers:
      - args:
        - start
        - --auto-build
        imagePullPolicy: Always
        name: keycloak
        ports:
        - containerPort: 8443
          protocol: TCP
        - containerPort: 8080
          protocol: TCP
        livenessProbe:
          exec:
            command:
              - curl
              - --insecure
              - --head
              - --fail
              - --silent
              - https://127.0.0.1:8443/health/live
          initialDelaySeconds: 20
          periodSeconds: 2
          failureThreshold: 100
        readinessProbe:
          exec:
            command:
              - curl
              - --insecure
              - --head
              - --fail
              - --silent
              - https://127.0.0.1:8443/health/ready
          initialDelaySeconds: 20
          periodSeconds: 2
          failureThreshold: 200
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
